name: ericks_planes
description: Play with Erick's planes and destroy your opponents!
version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
   - assets/images/plane.png
   - assets/images/plane-2.png
   - assets/images/clouds.png
   - assets/images/bullet-2.png
   - assets/images/explosion.png